import type { Metadata } from 'next'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { Inter as FontSans } from 'next/font/google'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import '@/styles/globals.css'
import Header from '@/components/Header'
import { Sidebar } from '@/components/Sidebar'
import MainContent from '@/components/MainContent'

const inter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

const fontClasses = [inter.className, 'antialiased'].join(' ')

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale} className={fontClasses}>
      <body className="flex flex-col min-h-screen">
        <Header />
        <div className="flex ">
          <div>
          
          <Sidebar />
          </div>
          <MainContent>{children}</MainContent>
        </div>
      </body>
    </html>
  )
}

export default RootLayout